# Generated by Django 5.0.2 on 2024-02-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cname', models.CharField(max_length=50)),
                ('image', models.ImageField(default='category.jpg', upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
