# Generated by Django 5.0.2 on 2024-03-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner_coupon_productoffer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='Amount',
            field=models.IntegerField(default=1),
        ),
    ]
