# Generated by Django 5.0.2 on 2024-03-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_total_amount_alter_wallet_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cat_start_date', models.DateTimeField(blank=True, null=True)),
                ('cat_end_date', models.DateTimeField(blank=True, null=True)),
                ('cat_active', models.BooleanField(default=False)),
            ],
        ),
    ]
