# Generated by Django 5.0.2 on 2024-03-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoryoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='products',
            field=models.ManyToManyField(related_name='offers', to='core.product'),
        ),
    ]
