# Generated by Django 5.0.2 on 2024-03-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productoffer_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='category',
            field=models.ManyToManyField(related_name='category_offers', to='core.category'),
        ),
    ]
