# Generated by Django 5.0.2 on 2024-03-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoryoffer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='category',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_offers', to='core.category'),
        ),
    ]
