# Generated by Django 5.0.2 on 2024-02-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_orderitem_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20),
        ),
    ]
