# Generated by Django 5.0.2 on 2024-02-28 12:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='Images',
            field=models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
