# Generated by Django 5.0.2 on 2024-03-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_status_alter_productimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='Images',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
    ]
